# Generated by Django 4.2.6 on 2023-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_sport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="time",
            field=models.TimeField(max_length=5),
        ),
    ]
