# Generated by Django 4.2.6 on 2023-11-22 09:14

import app.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_schedule_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="id",
            field=app.models.MyUUIDField(
                default=app.models.MyUUIDField.generate_uuid,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="id",
            field=app.models.MyUUIDField(
                default=app.models.MyUUIDField.generate_uuid,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
